"""add_user_session

Revision ID: d5240037248a
Revises:
Create Date: 2025-12-30 18:05:16.629765

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5240037248a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("hash_password", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number"),
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_users_id"), "users", ["id"], unique=False, schema="auth"
    )
    op.create_table(
        "user_sessions",
        sa.Column("device_id", sa.String(length=50), nullable=True),
        sa.Column("ip_addres", sa.String(length=15), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_user_sessions_id"),
        "user_sessions",
        ["id"],
        unique=False,
        schema="auth",
    )
    op.create_index(
        op.f("ix_auth_user_sessions_user_id"),
        "user_sessions",
        ["user_id"],
        unique=False,
        schema="auth",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_auth_user_sessions_user_id"), table_name="user_sessions", schema="auth"
    )
    op.drop_index(
        op.f("ix_auth_user_sessions_id"), table_name="user_sessions", schema="auth"
    )
    op.drop_table("user_sessions", schema="auth")
    op.drop_index(op.f("ix_auth_users_id"), table_name="users", schema="auth")
    op.drop_table("users", schema="auth")
    # ### end Alembic commands ###
